Import the dataset

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/MSSP6070/Assignment1/data_academic_performance.csv')

New groups of parents' education level

In [12]:
education_map = {
    'Postgraduate education': 'Graduate Degree',
    'Complete professional education': 'Bachelor’s Degree',
    'Incomplete Professional Education': 'Some College or Associate Degree',
    'Complete technique or technology': 'Some College or Associate Degree',
    'Complete Secundary': 'High School Completion',
    'Incomplete technical or technological': 'Less than High School',
    'Incomplete Secundary': 'Less than High School',
    'Complete primary': 'Less than High School',
    'Incomplete primary': 'Less than High School',
    'Ninguno': 'No Formal Education'
}
data['Father_EducationGroup'] = data['EDU_FATHER'].map(education_map)
data['Mother_EducationGroup'] = data['EDU_MOTHER'].map(education_map)
data[['EDU_FATHER', 'Father_EducationGroup', 'EDU_MOTHER', 'Mother_EducationGroup']].head()

,EDU_FATHER,Father_EducationGroup,EDU_MOTHER,Mother_EducationGroup
0,Incomplete Professional Education,Some College or Associate Degree,Complete technique or technology,Some College or Associate Degree
1,Complete Secundary,High School Completion,Complete professional education,Bachelor’s Degree
2,Not sure,NaN,Not sure,NaN
3,Not sure,NaN,Not sure,NaN
4,Complete professional education,Bachelor’s Degree,Complete professional education,Bachelor’s Degree

Mean quantitative reasoning score based on fathers' education level

In [13]:
mean_quant_by_father_edu = data.groupby('Father_EducationGroup')['QR_PRO'].mean().round(2).sort_values(ascending=False)
mean_quant_by_father_edu

Father_EducationGroup
Graduate Degree                     86.86
Bachelor’s Degree                   80.50
Some College or Associate Degree    78.56
High School Completion              74.71
Less than High School               74.08
No Formal Education                 73.24
Name: QR_PRO, dtype: float64

Mean quantitative reasoning score based on mothers' education level

In [14]:
mean_quant_by_mother_edu = data.groupby('Mother_EducationGroup')['QR_PRO'].mean().round(2).sort_values(ascending=False)
mean_quant_by_mother_edu

Mother_EducationGroup
Graduate Degree                     85.26
Bachelor’s Degree                   80.88
Some College or Associate Degree    78.51
High School Completion              75.00
Less than High School               74.10
No Formal Education                 72.24
Name: QR_PRO, dtype: float64

Mean critical reading score based on fathers' education level

In [15]:
mean_cr_by_father_edu = data.groupby('Father_EducationGroup')['CR_PRO'].mean().round(2).sort_values(ascending=False)
mean_cr_by_father_edu

Father_EducationGroup
Graduate Degree                     72.94
Bachelor’s Degree                   65.82
Some College or Associate Degree    65.49
No Formal Education                 60.46
High School Completion              58.97
Less than High School               58.50
Name: CR_PRO, dtype: float64

Mean critical reading score based on mothers' education level

In [16]:
mean_cr_by_mother_edu = data.groupby('Mother_EducationGroup')['CR_PRO'].mean().round(2).sort_values(ascending=False)
mean_cr_by_mother_edu

Mother_EducationGroup
Graduate Degree                     72.40
Bachelor’s Degree                   66.61
Some College or Associate Degree    64.46
High School Completion              58.87
Less than High School               57.49
No Formal Education                 49.21
Name: CR_PRO, dtype: float64

Outcomes based on Stratum

In [23]:
mean_scores_by_Stratum = (
    data[data['STRATUM'] != '0']
    .groupby('STRATUM')[['QR_PRO', 'CR_PRO', 'CC_PRO', 'ENG_PRO', 'WC_PRO', 'FEP_PRO']]
    .mean()
    .round(2)
)
mean_scores_by_Stratum

           QR_PRO  CR_PRO  CC_PRO  ENG_PRO  WC_PRO  FEP_PRO
STRATUM
Stratum 1   70.52   53.57   50.92    50.91   49.30   142.98
Stratum 2   74.62   58.82   55.96    60.95   51.15   142.48
Stratum 3   78.34   63.86   60.15    70.62   53.04   142.20
Stratum 4   83.22   69.27   66.97    80.10   59.59   154.05
Stratum 5   86.70   71.75   69.23    87.00   63.66   160.42
Stratum 6   88.36   73.76   71.07    92.45   65.59   162.17

Outcomes based on Socioeconomic Levels

In [25]:
mean_scores_by_SEL = (
    data.groupby('SEL')[['QR_PRO', 'CR_PRO', 'CC_PRO', 'ENG_PRO', 'WC_PRO', 'FEP_PRO']]
    .mean()
    .round(2)
)
mean_scores_by_SEL

     QR_PRO  CR_PRO  CC_PRO  ENG_PRO  WC_PRO  FEP_PRO
SEL
1     73.37   56.66   53.86    54.64   50.57   142.67
2     74.94   59.36   55.62    62.72   50.84   143.06
3     77.01   62.12   58.50    68.81   52.67   144.01
4     82.61   68.50   66.45    79.43   59.11   150.34

Mean Global Score Based on Gender

In [28]:
mean_scores_by_Gender = (
    data.groupby('GENDER')[['G_SC']]
    .mean()
    .round(2)
)
mean_scores_by_Gender

          G_SC
GENDER
F       161.28
M       163.69

Median Global Score Based on Gender

In [29]:
median_scores_by_Gender = (
    data.groupby('GENDER')[['G_SC']]
    .median()
    .round(2)
)
median_scores_by_Gender

         G_SC
GENDER
F       162.0
M       164.0